In [1]:
import csv
import pandas as pd

f = open('floating_population.csv')
fp =pd.DataFrame(csv.reader(f))
fp

,0,1,2,3,4,5,6,7,8,9,10
0,기준_년,기준_월,기준_일,행정동_명,시군구_코드,행정동_코드,서비스인구,주거인구,직장인구,방문인구,총 인구
1,2021,10,1,내외동,48250,4825054000,83037,64124.64595,8575.684366,10336.66968,83037
2,2021,10,2,내외동,48250,4825054000,82290,63547.78129,8498.537598,10243.68111,82290
3,2021,10,3,내외동,48250,4825054000,80438,62117.5894,8307.271446,10013.13915,80438
4,2021,10,4,내외동,48250,4825054000,81906,63251.24043,8458.879821,10195.87975,81906
...,...,...,...,...,...,...,...,...,...,...,...
6931,2022,9,26,회현동,48250,4825052000,9936,5365.548692,1461.402938,3109.04837,9936
6932,2022,9,27,회현동,48250,4825052000,11970,6463.930942,1760.566946,3745.502112,11970
6933,2022,9,28,회현동,48250,4825052000,10835,5851.018526,1593.629311,3390.352162,10835
6934,2022,9,29,회현동,48250,4825052000,6167,3330.247462,907.052327,1929.700211,6167
6935,2022,9,30,회현동,48250,4825052000,6338,3422.589333,932.2032834,1983.207384,6338