In [1]:
#pip install geopy

In [2]:
import pandas as pd
df = pd.read_csv('장애인전국체전_주소.csv',encoding='cp949')
df

                  주소
0          가야로 245-2
1   가야의길 98-19 (봉황동)
2       진영읍 진영리 1347
3            구산동 660
4      한림면 시산리 496-4
5      인제로 502 (삼방동)
6           관동동 1123
7      삼계로 132 (삼계동)
8         관동동 1123-1
9           율하동 1377
10  식만로 354-71 (불암동)

In [3]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent = 'South Korea')

def geocoding_lat(address):
    try:
        geo = geo_local.geocode(address)
        return geo.latitude
    
    except:
        return 0
    
    
def geocoding_lon(address):
    try:
        geo = geo_local.geocode(address)
        return geo.longitude
    
    except:
        return 0
    
df['위도'] = df['주소'].apply(geocoding_lat)
df['경도'] = df['주소'].apply(geocoding_lon)
df

                  주소         위도          경도
0          가야로 245-2  34.958864  127.712607
1   가야의길 98-19 (봉황동)  35.235831  128.872660
2       진영읍 진영리 1347  35.304312  128.733277
3            구산동 660  37.612281  126.908266
4      한림면 시산리 496-4   0.000000    0.000000
5      인제로 502 (삼방동)  35.252439  128.902718
6           관동동 1123  35.171160  128.794460
7      삼계로 132 (삼계동)  35.262985  128.875719
8         관동동 1123-1  35.171160  128.794460
9           율하동 1377  35.866520  128.690710
10  식만로 354-71 (불암동)  35.221645  128.925780

In [5]:
df.to_csv('장애인전국체전_위경도.csv', encoding = 'cp949', index = False)